services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - hackernews-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LOG_RETENTION_HOURS: 168
    networks:
      - hackernews-network
    healthcheck:
      test: [ "CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 40s

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8082:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - hackernews-network

  spark:
    image: grosinosky/spark:3.5.3
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8080:8080'
      - '7077:7077'
      - '18888:8888'

  spark-worker:
    image: grosinosky/spark:3.5.3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G # can be changed
      - SPARK_WORKER_CORES=3 # can be changed
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8081:8081'
    depends_on:
      - spark

  garage:
    image: grosinosky/garage:v2.1.0
    container_name: garage
    ports:
      - "3900:3900"  # S3 API
      - "3901:3901"  # RPC API
      - "3902:3902"  # s3 web
      - "3903:3903"  # admin API
    environment:
      # Garage configuration
      RUST_LOG: garage=info
    volumes:
      - garage-data:/var/lib/garage/data
      - garage-meta:/var/lib/garage/meta
    restart: unless-stopped
    networks:
      - hackernews-network

  garage-webui:
    image: khairul169/garage-webui:1.1.0
    container_name: garage-webui
    restart: unless-stopped
    ports:
      - 3909:3909
    environment:
      API_BASE_URL: "http://garage:3903"
      API_ADMIN_KEY: "changeme1234567890"
      S3_ENDPOINT_URL: "http://garage:3900"
    depends_on:
      - garage
    networks:
      - hackernews-network

  kafka-init-job:
    build:
      context: ./
      dockerfile: utils/Dockerfile
    container_name: kafka-job
    depends_on:
      kafka:
        condition: service_healthy
      kafka-connect-setup:
        condition: service_completed_successfully
      garage:
        condition: service_started
    networks:
      - hackernews-network

  kafka-connect:
    image: confluentinc/cp-kafka-connect:7.5.0
    hostname: kafka-connect
    container_name: kafka-connect
    depends_on:
      kafka:
        condition: service_healthy
      garage:
        condition: service_started
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'kafka:29092'
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: kafka-connect-s3
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
      CONNECT_LOG4J_ROOT_LOGLEVEL: "INFO"
      AWS_ACCESS_KEY_ID: "GKfa508def1ce303cbcf7c716d"
      AWS_SECRET_ACCESS_KEY: "b909152eeabfdc7ee998ea17d573fd7e3b1a436c80c9eca6d917753a5d4f18fd"
      CONNECT_LOG4J_LOGGERS: "org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR"
    networks:
      - hackernews-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/connectors"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command:
      - bash
      - -c
      - |
        confluent-hub install --no-prompt confluentinc/kafka-connect-s3:10.5.0
        /etc/confluent/docker/run

  kafka-connect-setup:
    image: confluentinc/cp-kafka-connect:7.5.0
    container_name: kafka-connect-setup
    depends_on:
      kafka-connect:
        condition: service_healthy
    networks:
      - hackernews-network
    environment:
      - CONNECT_URL=http://kafka-connect:8083
      - AWS_ACCESS_KEY_ID=GKff6ba2b3455ca4194ebe34c1
      - AWS_SECRET_ACCESS_KEY=81bd3b81dfe623301827b6fd5b9bea3fab1dea4aebac1e2793238655e37fe454
      - S3_BUCKET=bronze
      - S3_ENDPOINT=http://garage:3900
    command:
      - bash
      - -c
      - |
        curl -X POST http://kafka-connect:8083/connectors -H "Content-Type: application/json" -d '{
          "name": "s3-sink-hn-stories",
          "config": {
            "connector.class": "io.confluent.connect.s3.S3SinkConnector",
            "tasks.max": "1",
            "topics": "hn-stories",
            "s3.bucket.name": "bronze",
            "s3.region": "garage",
            "flush.size": "100",
            "storage.class": "io.confluent.connect.s3.storage.S3Storage",
            "format.class": "io.confluent.connect.s3.format.json.JsonFormat",
            "store.url": "http://garage:3900",
            "s3.path.style.access.enabled": "true"
          }
        }'
        curl -X POST http://kafka-connect:8083/connectors -H "Content-Type: application/json" -d '{
          "name": "s3-sink-hn-comments",
          "config": {
            "connector.class": "io.confluent.connect.s3.S3SinkConnector",
            "tasks.max": "1",
            "storage.class": "io.confluent.connect.s3.storage.S3Storage",
            "topics": "hn-comments",
            "s3.bucket.name": "bronze",
            "s3.region": "garage",
            "flush.size": "100",
            "format.class": "io.confluent.connect.s3.format.json.JsonFormat",
            "store.url": "http://garage:3900",
            "s3.path.style.access.enabled": "true"
          }
        }'
    restart: "no"

  silver-processor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: silver-processor
    volumes:
      - ./silver:/code
      - ./processor_common:/code/processor_common
    depends_on:
      kafka-init-job:
        condition: service_completed_successfully
      kafka-connect-setup:
        condition: service_completed_successfully
      garage:
        condition: service_started
      spark-worker:
        condition: service_started
    networks:
      - hackernews-network

  gold-processor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gold-processor
    volumes:
      - ./gold:/code
      - ./processor_common:/code/processor_common
    depends_on:
      silver-processor:
        condition: service_completed_successfully
    networks:
      - hackernews-network

volumes:
  garage-meta:
  garage-data:

networks:
  hackernews-network:
    driver: bridge
